### ISSUE TITLE
Any reason why the defaultOptions.html = false?

### ISSUE THREAD

**Issue by fpereira1** [Maldicore/Admin#1]
Good work on the plugin! I downloaded and worked great on my app automagically as you said.

I made a change to it to enable users to view HTML source when using the wysihtml5.

Just wondering, Any reason why the defaultOptions.html = false?

**Comment by yusuf** [comment]
This plugin uses https://github.com/jhollingworth/bootstrap-wysihtml5 and the wysihtml5 is initialized inside /app/Plugin/Admin/webroot/js/script.js

Rather than changing the defaultOptions (inside bootstrap-wysihtml5.js) you can change them inside script.js, so future upgrades of bootstrap-wysihtml5 will not change things:

The defaults are:

``` js
$('.textarea').wysihtml5({
        "font-styles": true, //Font styling, e.g. h1, h2, etc. Default true
        "emphasis": true, //Italics, bold, etc. Default true
        "lists": true, //(Un)ordered lists, e.g. Bullets, Numbers. Default true
        "html": false, //Button which allows you to edit the generated HTML. Default false
        "link": true, //Button to insert a link. Default true
        "image": true, //Button to insert an image. Default true,
        "color": false //Button to change color of font
    });
```

The latest repo has included them in script.js file and feel free to change them...
