### ISSUE TITLE
Incompatible with Plugins Behavior

### ISSUE THREAD

**Issue by eldad87** [Maldicore/Admin#6]
I have this model:

```
class Subject extends AppModel {
    public $name = 'Subject';
    public $useTable = 'subjects';
    public $primaryKey = 'subject_id';
    public $actsAs = array(
        'Lock',
        'LanguageFilter',
        'Uploader.Attachment' => array(
            'videoUpload'=>array(
                'uploadDir'             => 'vid/subjects/about_videos/',
                'appendNameToUploadDir' => true,
                'name'                  => 'formatFileName',
                'dbColumn'              => 'video_source'
            )
    );
}
```

I'm usig Miles' Uploader:
http://milesj.me/code/cakephp/uploader

Error I'm getting:
`Class 'Uploader' not found`

**Comment by yusuf** [comment]
The plugin comes with a basic upload feature, and uses Cake's scaffolds

But if you want to use Cake Miles' Uploader

Make sure composer is setup properly as it uses it... https://getcomposer.org/

Easiest way to do this in cake would be to use
https://github.com/uzyn/cakephp-composer

After that...

in your Config/core.php
require_once dirname(**DIR**) . '/Vendor/autoload.php';

Since this is not related with this plugin, I am closing it...
